LOAD DATA
INFILE 'C:\Oracle_Load\employees_100.csv'
INTO TABLE EMPLOYEES
APPEND
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  EMP_ID,
  EMP_NAME,
  DEPARTMENT,
  HIRE_DATE DATE "DD-MM-YYYY",
  SALARY
)