LOAD DATA 
INFILE 'C:\Oracle_Load\salary_data.csv'
INTO TABLE SALARY
APPEND
FIELDS TERMINATED BY ',' 
OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
EMP_ID,
SALARY_MONTH DATE "YYYY-MM",
GROSS_SALARY,
NET_SALARY,
BONUS
)	
